M48
; DRILL file {KiCad (6.0.2)} date Sun Jan 15 00:33:12 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-15T00:33:12-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1299
%
G90
G05
T1
X4.1488Y-1.3597
X4.6212Y-1.3597
T2
X3.215Y-0.975
X3.215Y-4.798
X10.088Y-0.975
X10.088Y-4.798
T3
X3.5343Y-4.69
X5.05Y-4.69
X6.3295Y-4.69
T0
M30
