site_name: LHRIC Monorepo Docs
theme:
  features:
    - content.tooltips
    - navigation.path
    - navigation.indexes
    - content.code.copy
  name: material
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
